### ISSUE TITLE
개발자 선택 페이지

### ISSUE THREAD

**Issue by dmdeh** [dmdeh/job-cracker#2]
## ✏️ 기능 설명
- 개발자 선택 페이지

## ✅ TODO
- [x] 당신은 어떤 개발자인가요? 질문 텍스트 렌더링
- [x] 백엔드, 프론트엔드, IOS 선택 가능
- [x] 구분 클릭 시 주제 선택 페이지로 라우팅
