### ISSUE TITLE
질문 답변 페이지

### ISSUE THREAD

**Issue by dmdeh** [dmdeh/job-cracker#5]
## ✏️ 기능 설명
- 질문 답변 페이지
## ✅ TODO
- [x] 질문 카드 컴포넌트
  - [x] 주제, 질문, 다른 주제 또는 답변 보기 버튼 표시
  - [x] #14
  - [x] #15
- [x] 답변 입력 textarea
