### ISSUE TITLE
시작 페이지

### ISSUE THREAD

**Issue by dmdeh** [dmdeh/job-cracker#6]
## ✏️ 기능 설명
- 시작 페이지
## ✅ TODO
- [x]  시작 텍스트 렌더링
- [x] 시작하기 버튼 렌더링
- [x] 시작하기 버튼 클릭 시 개발자 선택 페이지로 라우팅
